### PR TITLE
Add pm2_id as a part of notification title

### PR DESCRIPTION
**Pull request by abawchen**
Regarding: #15 
Inject `[pm2_id]` in to title and fallbackText, that title would be formatted as `name[pm2_id] event`, and fallbackText would be `name[pm2_id] event: description`.

### CODE REVIEW

**Comment by ma-zal** [comment]
I would like to see something more smart: Display IDs only if multiple processes with same name exist.
Is it possible? :-)

**Comment by mattpker** [comment]
@abawchen Thanks for the pull request!

Thinking about it now, I agree with @ma-zal, probably only need to show the pm2 process id for processes that are clustered.

Also, I don't know if I am ready for us to move to ES6+ code just yet (for example the `let`'s) because we don't know what version of node people are running. Let's keep it so it will run on older versions of node for now.

**Comment by abawchen** [comment]
@mattpker & @ma-zal 

Thanks for input, and I push a commit to show pm id only for clustered processes and switch back to ES5 syntax.
But I think we don't cover those processes running with `force` mode -- if we want to cover force mode, it has to get process description from `pm2.describe` to check if any process runs with the app name and wrap `scheduleSendToSlack` as a callback like:
```javascript
function parseProcessName(process, callback) {
    pm2.describe(process.name, function(err, processDescription) {
        var displayName = process.name + (processDescription.length > 1 ? '[' + process.pm_id + ']' : '');
        callback(displayName);
    });
}
```
```javascript
parseProcessName(data.process, function(name) {
    scheduleSendToSlack({
        name: name,
        event: data.event,
        description: description,
        timestamp: Math.floor(Date.now() / 1000),
    })
});
```
I am not sure is there an elegant way?

**Comment by ma-zal** [comment]
@abawchen Thanks. I'm merging the "cluster only" version. But we can try your next idea of function `parseProcessName` in separate branch. We have to try, if calling `pm2.describe()` have some performance impact.

**Comment by abawchen** [comment]
@ma-zal Thanks, it would be more complicated then I expect -- it has to call `pm2.connect` before calling `pm2.describe` -- maybe we have extract those pm2-related from `index.js` or it would be a little mess by putting them all together. So I just stop it before going further :p

**Pull request merged**
